travis:
  secure:
    BINSTAR_TOKEN: EZhmEoKlPAt27Mvim8o/Q6+nY/qr1nIyfpD0GVHbO2dL91mJd1uBTWjocNHZehY/qwWDXRucdbJoWYkDYvK0Bhs7GqGMaPr+OqoAsaqRN/OAy4tndIJKjWEC34cIUvbZ6zoSrGjHtmKzI3TyAc3Y6GzfOFDeK7HojPeO8UghCrbAhQyJMpfrZJyia7Nql6CX9VsOI+ZQqNT18BGLYNiIizdfauGT0aKY2TwIqfANWxuJNvKuTPoNx0CAdbmITkr3llKI3Sgk/UlrUDoxqnVNgumPct/dnCg1/8a5reDttLCvedAkkcNSr2WDyGBh6r7RcV6XYVD8el5ll2YSNAdT361J3xsS2sIyCZPwNcZ16pambQcRe4mWRzoaHvYaiXVD0jTTEtDaYk5NLrTYNlU3+p6ov7wW6gBBihBeNXMU+cRtPTUdCPJ/nPcApXwdWwkaz7Yh52yt5iNBkEw6uvRzJTUrOGhDfElzOeQ/InCDoGnQ/0iRdoWtLHnuc22rYsVX75w6dP9NUncL/bskwmG/zPFP/O8Z023AP2kK26O1zD0AQhRbvqQQziUA6Y2DvjXyHAs/JhQgtaxV4yqwqF3q4M8xmLtTCVSx/4KCN6D6G7YWPKrFvbazZdlziLKl93K7RfsWi9GgtjWV4hv29R0LR3DEtM5od4izU/8jANJ9Kqg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
